/**
 * Document Upload API Route
 * POST /api/documents/upload
 */

import { NextRequest, NextResponse } from "next/server";
import { v4 as uuidv4 } from "uuid";
import { parseDocument } from "@/lib/parser";
import { chunkDocument } from "@/lib/chunker";
import { generateEmbedding } from "@/lib/embeddings";
import { upsertChunks } from "@/lib/vector-store";
import { getServerSupabase } from "@/lib/supabase";
import type { DocType } from "@/types/document.types";
import { MAX_FILE_SIZE_BYTES, SUPPORTED_EXTENSIONS } from "@/config/constants";

export async function POST(request: NextRequest): Promise<NextResponse> {
  console.log("[Upload] Route called");
  try {
    const formData = await request.formData();
    const file = formData.get("file") as File | null;
    console.log("[Upload] FormData received, file:", file?.name);
    const docType = (formData.get("type") as DocType) || "other";
    const userId = formData.get("userId") as string;

    if (!file) {
      return NextResponse.json({ error: "No file provided" }, { status: 400 });
    }

    if (!userId) {
      return NextResponse.json({ error: "User ID required" }, { status: 401 });
    }

    // Validate file size
    if (file.size > MAX_FILE_SIZE_BYTES) {
      return NextResponse.json({ error: "File exceeds 50MB limit" }, { status: 400 });
    }

    // Validate file type
    const ext = file.name.slice(file.name.lastIndexOf(".")).toLowerCase();
    if (!SUPPORTED_EXTENSIONS.includes(ext as typeof SUPPORTED_EXTENSIONS[number])) {
      return NextResponse.json(
        { error: `Unsupported file type: ${ext}. Supported: ${SUPPORTED_EXTENSIONS.join(", ")}` },
        { status: 400 }
      );
    }

    const docId = uuidv4();
    const supabase = getServerSupabase();

    // Save initial document record
    const { error: insertError } = await supabase.from("documents").insert({
      id: docId,
      name: file.name,
      type: docType,
      status: "parsing",
      file_size: file.size,
      word_count: 0,
      chunk_count: 0,
      user_id: userId,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    });

    if (insertError) {
      console.error("[Upload] Failed to create document record:", insertError);
      return NextResponse.json({ error: "Failed to create document record" }, { status: 500 });
    }

    console.log(`[Upload] Parsing ${file.name} (${file.size} bytes)...`);

    // Parse document
    const buffer = Buffer.from(await file.arrayBuffer());
    const parsed = await parseDocument(buffer, file.type, file.name);

    console.log(`[Upload] Parsed: ${parsed.wordCount} words`);

    // Update status to chunking
    await supabase
      .from("documents")
      .update({ status: "chunking", word_count: parsed.wordCount })
      .eq("id", docId);

    // Chunk the document
    const chunks = chunkDocument({
      docId,
      docName: file.name,
      docType,
      content: parsed.text,
    });

    // Update status to embedding
    await supabase
      .from("documents")
      .update({ status: "embedding", chunk_count: chunks.length })
      .eq("id", docId);

    console.log(`[Upload] Generating embeddings for ${chunks.length} chunks...`);
    let embeddedCount = 0;
    
    // Generate embeddings — if rate-limited, skip and store chunk without embedding
    // The document will still be searchable via Full-Text Search (FTS).
    for (let i = 0; i < chunks.length; i++) {
      const embedding = await generateEmbedding(chunks[i].content);
      if (embedding) {
        chunks[i].embedding = embedding;
        embeddedCount++;
      }
    }
    
    if (embeddedCount === 0) {
      console.warn(`[Upload] No embeddings generated — FTS-only mode. Check GEMINI_API_KEYS quota.`);
    } else {
      console.log(`[Upload] Embedded ${embeddedCount}/${chunks.length} chunks.`);
    }

    // Store chunks (FTS tsvector is auto-generated by Postgres)
    await upsertChunks(chunks);

    console.log(`[Upload] Stored ${chunks.length} chunks in Supabase`);

    // Mark as ready
    await supabase
      .from("documents")
      .update({ status: "ready", updated_at: new Date().toISOString() })
      .eq("id", docId);

    return NextResponse.json({
      doc_id: docId,
      status: "ready",
      chunk_count: chunks.length,
      word_count: parsed.wordCount,
      embedded_count: embeddedCount,
    });
  } catch (error) {
    console.error("[Upload] Fatal Error:", error);
    const msg = error instanceof Error ? error.message : String(error);
    return NextResponse.json(
      { error: msg || "Unknown upload error" },
      { status: 500 }
    );
  }
}
